### ISSUE TITLE
YAML Wildcard Support (Feature Request/Suggestion)

### ISSUE THREAD

**Issue by gobshyte** [WASasquatch/was-node-suite-comfyui#212]
Hi
Any chance to introduce YAML file support for the wildcard processor node?
There is another set of custom nodes here, but they do not have seed or output like the awesome WAS nodes do... :(
https://github.com/adieyal/comfyui-dynamicprompts

**Comment by WASasquatch** [comment]
What is YAML wildcards?

**Comment by gobshyte** [comment]
Like this:
https://github.com/adieyal/sd-dynamic-prompts/blob/main/docs/SYNTAX.md#yaml-files
It allows weighting and nesting within the file :)

**Comment by gobshyte** [comment]
This person has made some great examples on CivitAI :
https://civitai.com/models/112041/billions-of-charaters-attires-ethnics-poses-paterns-expressions-makeups-hair-accesoires-bodyshapes-ages

**Comment by WASasquatch** [comment]
Interesting. Not sure I want to support it though. I do not like YAML as a user editable file because it's space sensitive. It's number one complaint with software that use it is broken configs, like Minecraft plugins. I also already have Noodle Soup Prompts which uses a single file too and is the predecessor to wildcards. Additionally, you can use weights just fine in wildcards in WAS-NS, eg
`(apple:1.3)`

**Comment by gobshyte** [comment]
Ok no worries, thanks for considering it :)
