### ISSUE TITLE
Feat Request: Output full filename in Image Save node

### ISSUE THREAD

**Issue by alessandroperilli** [WASasquatch/was-node-suite-comfyui#213]
As I wrote in a different Issue, it would be great if the Image Save node would have an output connector that exports the full filename of the image.

**Comment by WASasquatch** [comment]
That doesn't seem to be possible, as it breaks the images from showing. Seems to be some bug in ComfyUI. Didn't get any feedback on it when asking. 

You could always build your filenames and input them as the filename_prefix, and use prefix as filename mode.

**Comment by alessandroperilli** [comment]
Thanks for checking @WASasquatch. 

I'm not quite sure I understand your recommendation: I understand that I could build my filename structure and pass it as input to the Image Save node, but how would I capture the progressive number that ComfyUI automatically assigns to each new generation? 

I can't see a way to do that. What am I missing?

**Comment by WASasquatch** [comment]
That I'm not sure. But you could use the Number Counter to add number prefix that will count up each prompt run. Would only work for single images being saved, not batches though... I hope this can be fixed though, I don't think it's be design that you suddenly count have a image because you have an output.

**Comment by alessandroperilli** [comment]
OK, thank you. I'll close the issue even if there's no real solution.
