### ISSUE TITLE
Image Save Node: Return actual jpg file image output or add output for filepath

### ISSUE THREAD

**Issue by ckao10301** [WASasquatch/was-node-suite-comfyui#444]
Trying to use the Image Save node to save as jpg and output to the ComfyS3 Save Image to S3 node. The problem is, if I set the Image Save node to save as jpg, it outputs the uncompressed png to the ComfyS3 node.

1. Is it possible to add an image output for the actual compressed jpg?
2. Or, can we add an output for the filepath of the jpg file? 
Thanks

![image](https://github.com/user-attachments/assets/bce433fc-0760-4bcf-8457-1bec8904d4aa)

**Comment by TemryL** [comment]
Hi @ckao10301, I guess here the `Image Save` node from WAS simply return the image data in the same format it has been passed as input, not the jpeg file. And the `Save Image to S3` will actually always save the images in png and upload to s3. 

I guess here, one way to solve your issue would be to add the possibility to return the local path of the file generated by `Image Save` node and pass it to the simple `Upload File to S3` instead of `Save Image to s3` node.

**Comment by ckao10301** [comment]
it works, thanks!
