### ISSUE TITLE
Could you provide a tutorial for manually downloading the BLIP models?

### ISSUE THREAD

**Issue by raysers** [WASasquatch/was-node-suite-comfyui#458]
he two model boxes in the node cannot be freely selected; only Salesforce/blip-image-captioning-base and another Salesforce/blip-vqa-base are available. Due to network issues, the HUG download always fails. Could you provide a tutorial for manually downloading the BLIP models? Which directory should I download these two models to?

**Comment by WASasquatch** [comment]
HF uses cache objects at the location, so I am not sure if it's possible. And since you can't download with HF you also probably would fail to clone the repos, so not sure how to help you. The repos exist like:

![image](https://github.com/user-attachments/assets/73b77a84-15b7-4f34-8aaa-9694bc6cb2d0)

So you could if you really wanted to download every file one at a time from the site and put in folder named accordingly in the same folder structure of the repo.
