### ISSUE TITLE
numa error when install

### ISSUE THREAD

**Issue by kenyonxu** [WASasquatch/was-node-suite-comfyui#82]
![image](https://github.com/WASasquatch/was-node-suite-comfyui/assets/1241198/5864f18f-00f1-4e82-8709-7d653fd3ab2b)

**Comment by WASasquatch** [comment]
It's a typo in requirements. That should be "numba" with a B.

**Comment by DivinoAG** [comment]
I tried fixing that typo on the requirements file, but it doesn't seem like it's triggering Comfy to download the correct libraries. Is there anything else that needs to be done here?

**Comment by WASasquatch** [comment]
> I tried fixing that typo on the requirements file, but it doesn't seem like it's triggering Comfy to download the correct libraries. Is there anything else that needs to be done here?

I think numba comes with Python 3.10. The official numba website says to just try it, and doesn't specify to install. But it does have a pip package, so in case someone removed it, it would need to be reinstalled. I didn't need to install it to use it myself with ComfyUI portable, it was already there.

**Comment by DivinoAG** [comment]
Well, I never did anything related to it (I'm not a developer, so I never touch anything related to Python, nor was I aware of numba's existence until today), and your addon is no longer working since this update. Below is the error message from Comfy even after I made the change to the requirements file to `numba` instead of `numa`.

![image](https://github.com/WASasquatch/was-node-suite-comfyui/assets/5044664/ff42705e-966b-4082-b9dd-3ade41762f87)

**Comment by WASasquatch** [comment]
Did you not re-run the requirements after it was patched? You should always be sure to run the requirements with new changes, as their may be new requirements, like numba. 

`C:\path\to\ComfyUI\python_embeded\python.exe -s -m pip install -r requirements.txt`

Or numba directly
`C:\path\to\ComfyUI\python_embeded\python.exe -s -m pip install numba`

**Comment by DivinoAG** [comment]
I assumed that happened when Comfy is starting. I guess that's my mistake.
